name: Continuous Integration
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install doxygen
        run: sudo apt-get install doxygen
      - name: Configure
        run: ./configure
      - name: Build & package
        run: make build doc dev_doc
