name: Continuous Integration
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install doxygen graphviz gcovr valgrind
      - name: Configure
        run: ./configure
      - name: Run checks
        run: make rungcov valgrindu runtestc valgrindc
      - name: Build & package
        run: make build doc dev_doc deb
